uk_postcode_validator/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from validator import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^validate/', views.validate, name="validate"),
    # url(r'^input/', views.index, name="index")
    url(r'^', include('validator.urls'))


]

validator/urls.py
from django.conf.urls import url
from . import views


app_name = 'validator'
urlpatterns = [

    # /validate
    url(r'^validate/', views.validate, name="validate"),

    # /input
    url(r'^input/', views.index, name="index"),

    # /
    url(r'^', views.index, name="index")
]

validator/models.py
from django.db import models

# Create your models here.

validator/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . import validation


def index(request):

    return render (request, 'validator/index.html')


def validate(request):

    if(request.method == "POST"):
        code = request.POST["postcode"]
        if validation.is_valid(code):
            code_status = 'valid'
        else:
            code_status ='invalid'
        return render (request, 'validator/result.html', {'code_status':code_status})

validator/templates/validator/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% load staticfiles%}
        <link rel="stylesheet" href="{% static 'validator/Semantic-UI-CSS-master/semantic.min.css'%}">
        <title></title>
    </head>
    <body>
        <form  action="{% url 'validator:validate'%}" method="POST">
            {% csrf_token %}
            <div class="ui action input">
                <input name="postcode" type="text">
                <button class="ui button" type="submit">Verify</button>
            </div>
        </form>
    </body>
</html>

validator/templates/validator/result.html
you post code is  {{code_status}}